using MongoDB.Bson.Serialization.Attributes;

namespace EprRegisterEnrolManagementBe.WorkItems.ReAccreditation.Models;

/// <summary>
/// Payload shape captured at the front-of-funnel ingestion of a
/// re-accreditation work item. Just enough fields to drive the
/// <see cref="IReAccreditationDecisionService"/> recommendation.
///
/// Stored on the work item envelope as a free-form BSON sub-document; this
/// record is the module's interpretation of that document, deserialised on
/// demand when the module needs to reason about the payload.
///
/// Marked <see cref="BsonIgnoreExtraElementsAttribute"/> so envelope-level
/// fields stamped onto the payload by the core <c>WorkItemService</c>
/// (e.g. <c>applicationReference</c>, <c>source</c>, <c>siteAddressLine1</c>)
/// do not cause deserialisation to fail when the module re-reads its
/// own slice of the payload.
/// </summary>
[BsonIgnoreExtraElements]
internal sealed record ReAccreditationPayload
{
    public string? OrganisationName { get; init; }
    public string? RegistrationNumber { get; init; }
    public List<string>? MaterialsHandled { get; init; }
    public int? PreviousAccreditationYear { get; init; }
    public int? ComplianceIssuesReported { get; init; }

    /// <summary>
    /// Operator email address used as the GOV.UK Notify recipient for
    /// the lifecycle email templates wired up by
    /// <c>ReAccreditationNotificationHook</c> (RA-123). Optional —
    /// notifications are skipped (and recorded as such in the audit
    /// log) when missing.
    /// </summary>
    public string? OperatorEmail { get; init; }

    /// <summary>
    /// Postcode of the regulated site. Used by <c>ReAccreditationNationRoutingHook</c>
    /// (RA-125) to derive the <see cref="Nation"/> field via
    /// <see cref="INationResolver"/>. Optional — when absent the nation
    /// defaults to <see cref="Nation.England"/>.
    /// </summary>
    public string? SiteAddressPostcode { get; init; }

    /// <summary>
    /// The UK nation to which this application is routed, derived from
    /// <see cref="SiteAddressPostcode"/> by <c>ReAccreditationNationRoutingHook</c>
    /// (RA-125). Written by the server at submission time; callers should
    /// not include it in the submission payload.
    /// </summary>
    public Nation? Nation { get; init; }

    /// <summary>
    /// Issued accreditation identifier (RA-132). Generated by the
    /// approval service when a decision-maker approves the application.
    /// </summary>
    public string? AccreditationId { get; init; }

    /// <summary>
    /// Date the issued accreditation takes effect (RA-132). Stamped by
    /// the approval service at the moment of approval.
    /// </summary>
    public DateOnly? AccreditationStartDate { get; init; }

    /// <summary>
    /// Four-digit accreditation year stamped at approval time
    /// (RA-133). Sourced from the <c>Accreditation:CurrentYear</c>
    /// configuration setting and used to derive both the year segment
    /// of <see cref="AccreditationId"/> and the
    /// <see cref="AccreditationStartDate"/>.
    /// </summary>
    public int? AccreditationYear { get; init; }

    /// <summary>
    /// RA-132 SLA clock state. Set by the approval service when the
    /// clock is stopped on approval.
    /// </summary>
    public SlaClock? SlaClock { get; init; }
}
